sudo: required
dist: trusty
language: c
compiler:
  - gcc
before_install:
  - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  - sudo apt-get update -q
install:
  - sudo apt-get install -y --force-yes gcc-arm-embedded
script:
  - cd stereoboard && make submodule && make

